version: "3.8"

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    env_file:
      - ./Backend/.env
    environment:
      - MONGODB_URI=mongodb://mongo:27017
    ports:
      - "5300:3000"
    restart: unless-stopped
    depends_on:
      - mongo

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        VITE_BASE_URL: ${VITE_BASE_URL:-https://nss.iitr.ac.in/jee/api}
    ports:
      - "5180:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo_data:
