version: "3.8"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    env_file:
      - ./Backend/.env
    ports:
      - "5300:3000"
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        VITE_BASE_URL: ${VITE_BASE_URL:-https://nss.iitr.ac.in/jee/api}
    ports:
      - "5180:6000"
    depends_on:
      - backend
    restart: unless-stopped
