version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: CrackItHub
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - crackit_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # The compose file will ensure the app connects to the internal mongo service.
      - MONGODB_URI=mongodb://mongo:27017
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - crackit_net

volumes:
  mongo-data:

networks:
  crackit_net:
    driver: bridge
